/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unisinos.estruturas.trabalho.gb.gui;

import br.unisinos.estruturas.trabalho.gb.entity.Pessoa;
import br.unisinos.estruturas.trabalho.gb.enumerador.Tipo;
import br.unisinos.estruturas.trabalho.gb.ui.MenuUI;
import java.text.ParseException;

import javax.swing.*;
import javax.swing.text.DefaultFormatter;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author diego
 */
public class TelaDeConsultaJF<jListaPesquisa> extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeConsultaJF
     */
    public TelaDeConsultaJF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListaPesquisa = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jrCpf = new javax.swing.JRadioButton();
        jrNome = new javax.swing.JRadioButton();
        jrData = new javax.swing.JRadioButton();
        ftDataInicio = new javax.swing.JFormattedTextField();
        ftDataFim = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblBuscaPor = new javax.swing.JLabel();
        btPesquisar = new javax.swing.JButton();
        ftNomeCpf = new javax.swing.JFormattedTextField();
        lblInfos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BUSCA DE REGISTROS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jListaPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder("Chaves Encontrados na AVL:"));
        jListaPesquisa.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jListaPesquisaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jListaPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListaPesquisaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListaPesquisa);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Buscar por:"));
        jPanel1.setName(""); // NOI18N

        jrCpf.setText("CPF");
        jrCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrCpfActionPerformed(evt);
            }
        });

        jrNome.setSelected(true);
        jrNome.setText("Nome");
        jrNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrNomeActionPerformed(evt);
            }
        });

        jrData.setText("Data");
        jrData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrDataActionPerformed(evt);
            }
        });

        try {
            ftDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftDataInicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        try {
            ftDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftDataFim.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setText("Data Início:");

        jLabel2.setText("Data Fim:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrNome)
                .addGap(18, 18, 18)
                .addComponent(jrCpf)
                .addGap(39, 39, 39)
                .addComponent(jrData)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ftDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ftDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrData)
                            .addComponent(jrCpf)
                            .addComponent(jrNome))
                        .addGap(6, 6, 6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblBuscaPor.setText("Informe o nome:");

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search48.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        try {
            ftNomeCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBuscaPor)
                    .addComponent(ftNomeCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblBuscaPor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ftNomeCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lblInfos.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        lblInfos.setText("Informe um nome para procurar na árvore AVL:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInfos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInfos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

//        lblBuscaPor.setText("Informe o nome:");
    }//GEN-LAST:event_formWindowActivated

    private void jrNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrNomeActionPerformed

        jrNome.setSelected(true);
        lblBuscaPor.setText("Informe o nome:");
        ftNomeCpf.setEnabled(true);
        formatarFtNomeCpfByNome();
        jrCpf.setSelected(false);
        jrData.setSelected(false);
        ftDataInicio.setEnabled(false);
        ftDataFim.setEnabled(false);
        lblInfos.setText("Informe um nome no campo acima para verificar na árvore AVL");
        jListaPesquisa.setModel(new DefaultListModel<>());

    }//GEN-LAST:event_jrNomeActionPerformed

    private void jrCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrCpfActionPerformed

        jrNome.setSelected(false);
        jrCpf.setSelected(true);
        lblBuscaPor.setText("Informe o CPF:");
        ftNomeCpf.setEnabled(true);
        formatarFtNomeCpfByCpf();
        jrData.setSelected(false);
        ftDataInicio.setEnabled(false);
        ftDataFim.setEnabled(false);
        lblInfos.setText("Informe um CPF no campo acima para verificar na árvore AVL");
        jListaPesquisa.setModel(new DefaultListModel<>());

    }//GEN-LAST:event_jrCpfActionPerformed

    private void formatarFtNomeCpfByCpf() {
        try {
            ftNomeCpf.setValue(null);
            ftNomeCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (ParseException ex) {
            Logger.getLogger(TelaDeConsultaJF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void formatarFtNomeCpfByNome() {
        ftNomeCpf.setValue(null);
        ftNomeCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new DefaultFormatter()));
    }

    private void jrDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrDataActionPerformed

        jrNome.setSelected(false);
        jrCpf.setSelected(false);
        jrData.setSelected(true);
        ftNomeCpf.setEnabled(false);
        ftDataInicio.setEnabled(true);
        ftDataFim.setEnabled(true);
        lblInfos.setText("Informe uma data inicial e final para verificar na árvore AVL");
        jListaPesquisa.setModel(new DefaultListModel<>());

    }//GEN-LAST:event_jrDataActionPerformed

    @SuppressWarnings("empty-statement")
    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed

        retornoDasBuscas = "";
        jListaPesquisa.setModel(new DefaultListModel<>());
        

        if(jrNome.isSelected()) {
            
            if(ftNomeCpf.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Favor insira um nome para buscar", "Campo Vazio", 0);
                return;
            }

            MenuUI.arvoreAVLNOME.buscarAsPessoasNaAVLPorNomeEImprimirEmOrdem(MenuUI.arvoreAVLNOME.raiz, ftNomeCpf.getText());
            
            if(retornoDasBuscas.equals("")) {
                lblInfos.setText("Nenhum valor foi encontrado!");
                JOptionPane.showMessageDialog(null,"Nenhum valor foi encontrado!");
            } else {
                lblInfos.setText("Selecione uma chave abaixo para visualizar mais informações");
            }
            jListaPesquisa.setModel(listaModelDePesquisa(retornoDasBuscas, Tipo.NOME));

        } else if (jrCpf.isSelected()) {
            
            if(ftNomeCpf.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Favor insira um CPF para buscar", "Campo Vazio", 0);
                return;
            }
            
            MenuUI.arvoreAVLCPF.buscarPeloCPF(ftNomeCpf.getText());
            
            if(retornoDasBuscas.equals("")) {
                lblInfos.setText("Nenhum valor foi encontrado!");
                JOptionPane.showMessageDialog(null,"Nenhum valor foi encontrado!");
            } else {
                lblInfos.setText("Selecione uma chave abaixo para visualizar mais informações");
            }
            
            jListaPesquisa.setModel(listaModelDePesquisa(retornoDasBuscas, Tipo.CPF));
            
        } else if (jrData.isSelected()) {

            MenuUI.arvoreAVLDATA.consultarTodasPessoasPorDataEmOrdem(MenuUI.arvoreAVLDATA.raiz, dataFormatada(ftDataInicio.getText()), dataFormatada(ftDataFim.getText()));

            if(retornoDasBuscas.equals("")) {
                lblInfos.setText("Nenhum valor foi encontrado!");
                JOptionPane.showMessageDialog(null,"Nenhum valor foi encontrado!");
            } else {
                lblInfos.setText("Selecione uma chave abaixo para visualizar mais informações");
            }
            
            jListaPesquisa.setModel(listaModelDePesquisa(retornoDasBuscas, Tipo.DATA));

        } else {
            String[] pesquisar = null;
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private LocalDate dataFormatada(String data) {
        return LocalDate.parse(data, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
    }

    /**
     * Método que recebe uma String contendo valores separados por ";". Essa String será inserida em array de String onde cada elemento será inserido em
     * uma variavel do tipo ListModel, retornando-a.
     * @param retornoDasBuscas - String que contem um ou mais valores separados por ";".
     * @return Retorna um ListModel do tipo String contendo valores para usar em uma JList.
     */
    private ListModel<String> listaModelDePesquisa(String retornoDasBuscas, Tipo pesquisaPor) {

        DefaultListModel model = new DefaultListModel();

        String[] pesquisar = retornoDasBuscas.split(";");
        for (String busca : pesquisar) {
            model.addElement(modelDeBuscaEQuantidade(busca, pesquisaPor));
        }

        return model;
    }

    private String modelDeBuscaEQuantidade(String busca, Tipo pesquisaPor) {
        Integer contador = 0;

        for (Pessoa pessoa : MenuUI.pessoas) {
            if (pesquisaPor == Tipo.DATA) {
                if (busca.equals(pessoa.getData().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")))) {
                    contador++;
                }
            } else if (pesquisaPor == Tipo.CPF) {
                if (busca.equals(pessoa.getCpf())) {
                    contador++;
                }
            } else if (pesquisaPor == Tipo.NOME) {
                if (busca.equals(pessoa.getNome())) {
                    contador++;
                }
            }
        }
        return String.format("%s%s", busca, (contador > 1 ? "-(" + contador + ")": ""));
    }


    private void jListaPesquisaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jListaPesquisaAncestorAdded
        //
    }//GEN-LAST:event_jListaPesquisaAncestorAdded

    private void jListaPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListaPesquisaMouseClicked

        String pessoa = "";
        String valorSelecionadoNaLista = jListaPesquisa.getSelectedValue().toString();

        if(jrNome.isSelected()) {
            pessoa = buscarDadosDeUmaPessoaByParametro(valorSelecionadoNaLista.split("-")[0], Tipo.NOME);

        } else if (jrCpf.isSelected()) {
            pessoa = buscarDadosDeUmaPessoaByParametro(valorSelecionadoNaLista.split("-")[0], Tipo.CPF);

        } else {
            pessoa = buscarDadosDeUmaPessoaByParametro(valorSelecionadoNaLista.split("-")[0], Tipo.DATA);

        }

        JOptionPane.showMessageDialog(null, pessoa.toString(),"Dados da Pessoa:", 1);


    }//GEN-LAST:event_jListaPesquisaMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jrNome.setSelected(true);
        lblBuscaPor.setText("Informe o nome:");
        ftNomeCpf.setEnabled(true);
        formatarFtNomeCpfByNome();
        jrCpf.setSelected(false);
        jrData.setSelected(false);
        ftDataInicio.setEnabled(false);
        ftDataFim.setEnabled(false);
        lblInfos.setText("Informe um nome no campo acima para verificar na árvore AVL");
    }//GEN-LAST:event_formWindowOpened

    private String buscarDadosDeUmaPessoaByParametro(String valorAPesquisar, Tipo buscarPor) {
        String pessoas = "";

        for (Pessoa pessoa : MenuUI.pessoas) {
            if (buscarPor == Tipo.DATA) {
                if (valorAPesquisar.equals(pessoa.getData().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")))) {
                    pessoas += pessoa.toString() + "\n";
                }
            } else if (buscarPor == Tipo.CPF) {
                if (valorAPesquisar.equals(pessoa.getCpf())) {
                    pessoas += pessoa.toString() + "\n";
                }
            } else if (buscarPor == Tipo.NOME) {
                if (valorAPesquisar.equals(pessoa.getNome())) {
                    pessoas += pessoa.toString() + "\n";
                }
            }
        }
        return pessoas;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeConsultaJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeConsultaJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeConsultaJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeConsultaJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeConsultaJF().setVisible(true);
            }
        });
    }
    
    public static String retornoDasBuscas;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPesquisar;
    private javax.swing.JFormattedTextField ftDataFim;
    private javax.swing.JFormattedTextField ftDataInicio;
    private javax.swing.JFormattedTextField ftNomeCpf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListaPesquisa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrCpf;
    private javax.swing.JRadioButton jrData;
    private javax.swing.JRadioButton jrNome;
    private javax.swing.JLabel lblBuscaPor;
    private javax.swing.JLabel lblInfos;
    // End of variables declaration//GEN-END:variables
}
